export const ROUTES = {
  ROOT: '/',
  AUTH: {
    INDEX: '/auth',
  },
  APP: {
    MARKETPLACE: '/marketplace',
    CATEGORIES: {
      ROOT: '/categories',
      DOMAINS: {
        ROOT: '/categories/domains',
        DETAILS: (id: number) => `/categories/domains/${id}`,
      },
      WEBSITES: '/categories/websites',
      APPS: '/categories/apps',
      FBA_STORES: '/categories/fba-stores',
      E_COMMERCE: '/categories/e-commerce',
      SOFTWARE_SAAS: '/categories/software-saas',
      DATABASES: '/categories/databases',
      DIGITAL_CHANNELS: '/categories/digital-channels',
      NFTs: '/categories/nfts',
    },
  },
  CLIENT: {
    ROOT: '/client',
    FACTURAS: '/client/facturas',
    AUCTIONS: '/client/auctions',
    DASHBOARD: '/client/dashboard',
    FAQ: '/client/faq',
    ORDERS: {
      INDEX: '/client/orders',
      ALL: '/client/orders/all',
      ORDER_DETAILS: (id: number) => `/client/orders/${id}`,
      INVOICES: '/client/orders/invoices',
      PAYMENTS: '/client/orders/payments',
      ESCROWS: '/client/orders/escrows',
    },
    MARKETPLACE: {
      ROOT: '/client/marketplace',
      MY_LISTINGS: '/client/marketplace/my-listings',
      MY_LISTINGS_DETAILS: (id: number) => `/client/marketplace/my-listings/${id}`,
      PRODUCTS_VERIFICATION: '/client/marketplace/products-verification',
      PRODUCTS_VERIFICATION_DETAILS: (id: number) => `/client/marketplace/products-verification/${id}`,
      APPS: '/client/marketplace/apps',
      DOMAINS: '/client/marketplace/domains',
      WEBSITES: '/client/marketplace/websites'
    },
    OFFERS: {
      INDEX: '/client/offers',
      DETAILS: (id: number) => `/client/offers/${id}`,
    },
    PROFILE: '/client/profile',
    PROFILE_SETUP: '/client/profile-setup',
    SAVED_SEARCH: '/client/saved-search',
    SUPPORT: '/client/support',
    CHAT: {
      ROOT: '/client/chat',
      CONVERSATION: (id: number) => `/client/chat/${id}`,
    },
    REVIEWS: '/client/reviews',
  },
  ADMIN: {
    ROOT: "/admin",
    DASHBOARD: "/admin/dashboard",
    ANALYTICS: "/admin/analytics",
    USERS: "/admin/users",
    USER_DETAILS: (id: number | string) => `/admin/users/${id}`,
    ROLES_PERMISSIONS: "/admin/roles-and-permissions",
    BLOG_MANAGER: "/admin/blog-manager",
    FAQ_MANAGER: "/admin/faq-manager",
    LISTINGS_MANAGEMENT: "/admin/listings-management",
    ORDERS: {
      LIST: "/admin/orders",
      DETAILS: (id: number) => `/admin/orders/${id}`,
      INVOICES:(id: number) => `/admin/orders/${id}/invoices`,
      PAYMENTS:(id: number) => `/admin/orders/${id}/payments`,
      ESCROWS:(id: number) => `/admin/orders/${id}/escrows`,
    },
    SUPPORT: "/admin/support",
    OFFERS: "/admin/offers",
    CATEGORIES: {
      SUPPORT: "/admin/categories/support",
      FAQ: "/admin/categories/faq",
      BLOG: "/admin/categories/blog"
    },
    NOTIFICATIONS: "/admin/notifications",
    UPLOADS: "/admin/uploads",
    VERIFICATIONS: "/admin/verifications",
    DISPUTES: "/admin/disputes",
    VALUATIONS: "/admin/valuations",
    SOCIAL: "/admin/social",
    PROFILE: "/admin/profile",
    SECURE_BOX: "/admin/secure-box",
  },
}; 