export const ROUTES = {
  ROOT: "/",
  AUTH: {
    INDEX: "/auth",
  },
  APP: {
    MARKETPLACE: "/marketplace",
    CATEGORIES: {
      ROOT: "/categories",
      BY_SLUG: (slug: string) => `/categories/${slug}`,
      LISTING_DETAIL: (slug: string, listingSlug: string) =>
        `/categories/${slug}/${listingSlug}`,
      DOMAINS: {
        ROOT: "/categories/domains",
        DETAILS: (listingSlug: string) => `/categories/domains/${listingSlug}`,
      },
    },
    LISTING_DETAIL: (listingSlug: string) => `/listings/${listingSlug}`,
    HELP_GUIDES: {
      ROOT: "/help-and-guides",
      CATEGORY: (slug: string) => `/help-and-guides/category/${slug}`,
      ARTICLE: (slug: string) => `/help-and-guides/article/${slug}`,
    },
    BLOG: {
      ROOT: "/blog",
      DETAILS: (slug: string) => `/blog/${slug}`,
      CATEGORY: (category: string) => `/blog/category/${category}`,
    },
  },
  CLIENT: {
    ROOT: "/client",
    WALLET: (type?: string) =>
      type ? `/client/wallet?type=${type}` : "/client/wallet",
    FACTURAS: "/client/facturas",
    AUCTIONS: "/client/auctions",
    DASHBOARD: "/client/dashboard",
    FAQ: "/client/faq",
    ORDERS: {
      INDEX: "/client/orders",
      ALL: "/client/orders/all",
      ORDER_DETAILS: (id: number) => `/client/orders/${id}`,
      INVOICES: "/client/orders/invoices",
      PAYMENTS: "/client/orders/payments",
      ESCROWS: "/client/orders/escrows",
    },
    MARKETPLACE: {
      ROOT: "/client/marketplace",
      MY_LISTINGS: "/client/marketplace/my-listings",
      MY_LISTINGS_DETAILS: (id: number) =>
        `/client/marketplace/my-listings/${id}`,
      PRODUCTS_VERIFICATION: "/client/marketplace/products-verification",
      PRODUCTS_VERIFICATION_DETAILS: (id: number) =>
        `/client/marketplace/products-verification/${id}`,
    },
    OFFERS: {
      INDEX: "/client/offers",
      DETAILS: (id: number) => `/client/offers/${id}`,
    },
    PROFILE: "/client/profile",
    PROFILE_SETUP: "/client/profile-setup",
    SAVED_SEARCH: "/client/saved-search",
    SUPPORT: "/client/support",
    SUPPORT_TICKET: (id: number) => `/client/support/tickets/${id}`,
    CHAT: {
      ROOT: "/client/chat",
      CONVERSATION: (id: number) => `/client/chat/${id}`,
    },
    REVIEWS: "/client/reviews",
  },
  ADMIN: {
    ROOT: "/admin",
    REPORTS: {
      OVERVIEW: "/admin/reports/overview",
      REVENUE: "/admin/reports/revenue",
      USERS: "/admin/reports/users",
      LISTINGS: "/admin/reports/listings",
      ORDERS: "/admin/reports/orders",
      PAYMENTS: "/admin/reports/payments",
      ESCROW: "/admin/reports/escrow",
      WITHDRAWALS: "/admin/reports/withdrawals",
      DISPUTES: "/admin/reports/disputes",
      SUPPORT: "/admin/reports/support",
      AUCTIONS: "/admin/reports/auctions",
      INVOICES: "/admin/reports/invoices",
    },
    DASHBOARD: "/admin/dashboard",
    ANALYTICS: "/admin/analytics",
    USERS: "/admin/users",
    USER_DETAILS: (id: number | string) => `/admin/users/${id}`,
    ROLES_PERMISSIONS: "/admin/roles-and-permissions",
    BLOG_MANAGER: "/admin/blog-manager",
    FAQ_MANAGER: "/admin/faq-manager",
    LISTINGS_MANAGEMENT: "/admin/listings-management",
    PAYMENTS: "/admin/payments",
    PAYMENT_DETAILS: (id: number | string) => `/admin/payments/${id}`,
    ORDERS: {
      LIST: "/admin/orders",
      DETAILS: (id: number) => `/admin/orders/${id}`,
      INVOICES: (id: number) => `/admin/orders/${id}/invoices`,
      PAYMENTS: (id: number) => `/admin/orders/${id}/payments`,
      ESCROWS: (id: number) => `/admin/orders/${id}/escrows`,
    },
    SUPPORT: "/admin/support",
    SUPPORT_TICKET: (id: number) => `/admin/support/tickets/${id}`,
    OFFERS: "/admin/offers",
    CATEGORIES: {
      LISTINGS: "/admin/categories/listings",
      SUPPORT: "/admin/categories/support",
      FAQ: "/admin/categories/faq",
      BLOG: "/admin/categories/blog",
    },
    GUIDES: {
      CATEGORIES: "/admin/guides/categories",
      ARTICLES: "/admin/guides/articles",
      ARTICLE_EDIT: (id: number | "new") => `/admin/guides/articles/${id}`,
    },
    NOTIFICATIONS: "/admin/notifications",
    UPLOADS: "/admin/uploads",
    VERIFICATIONS: "/admin/verifications",
    DISPUTES: "/admin/disputes",
    VALUATIONS: "/admin/valuations",
    SOCIAL: "/admin/social",
    PROFILE: "/admin/profile",
    SECURE_BOX: "/admin/secure-box",
    SETTINGS: "/admin/settings",
    TRANSLATIONS: "/admin/translations",
  },
};
